# Generated by Django 3.2.6 on 2021-08-11 14:32

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210801_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, default='', upload_to=blog.models.upload_thumbnail_to),
        ),
    ]
